version: '3.8'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    networks: 
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - "9000"
    restart: on-failure


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/oloncle/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/oloncle/data/mariadb'

networks:
  inception:
    driver: bridge
